 export const events = [
    // {
    //   title: "None",
    //   date: "TBA",
    //   place: "📍TBA",
    //   desc: "จิงโจ้", 
    //   image: "/event1.jpg", 
    //   link: "",
    // }, 
    {
      title: "Kangaroo Village Christmas Festival",
      date: "19 – 21 ธันวาคม 2025",
      place: "📍 MCC HALL 3F, The Mall Bangkae",
      desc: "จิงโจ้",
      image: "/event1.jpg",
      link: "https://www.facebook.com/share/p/1ABrNvjBWq/",
      lastShowDate: new Date(2025, 11, 21, 23, 59, 59),
    }, 
    {
      title: "Handshake Event",
      date: "27-28 ธันวาคม 2025",
      place: "📍 MCC HALL 3F, The Mall Bangkapi",
      desc: "งานจับมือ",
      image: "/event2.jpg",
      link: "https://www.facebook.com/share/p/1FhYtAqPCE/",
      lastShowDate: new Date(2025, 11, 28, 23, 59, 59),
    }, 
    {
      title: "War of Goddess",
      date: "15 กุมภาพันธ์ 2026",
      place: "📍 TBA",
      desc: "กีฬาสี",
      image: "/event3.jpg",
      link: "https://www.facebook.com/share/p/16yQFhDc2G/",
      lastShowDate: new Date(2026, 1, 15, 23, 59, 59),
    }, 
    {
      title: "BNK48 & CGM48 Siam-Nippon Summer Fest 2026",
      date: "27-29 มีนาคม 2026",
      place: "JJ Hall @JJ Mall, Bangkok",
      image: "/SummerFest.jpg",
      link: "https://www.facebook.com/share/p/1AciNQ6BVq/",
      lastShowDate: new Date(2026, 2, 29, 23, 59, 59),
    },
    {
      title: "แค่เพียงมีเธอ Press Tour",
      date: "8 เมษายน 2026",
      place: "",
      image: "/Presstour.jpg",
      link: "https://www.facebook.com/share/p/1SrowXE8KU/",
      lastShowDate: new Date(2026, 3, 4, 23, 59, 59),
    },
    {
      title: "THAI LIZM Music Festival 2026",
      date: "13 เมษายน 2026",
      place: "📍Outdor Square @CentralWorld, Bangkok",
      image: "/Thailizm.jpg",
      link: "https://www.facebook.com/share/p/18QTvSwCUQ/",
      lastShowDate: new Date(2026, 3, 13, 23, 59, 59),
    },
    {
      title: "Shock Me Girls: LOCKER BOX",
      date: "16 พฤษภาคม 2026",
      place: "📍Paradise Park, Bangkok",
      image: "/smglocker.jpg",
      link: "https://www.facebook.com/share/p/18QTvSwCUQ/",
      lastShowDate: new Date(2026, 4, 16, 23, 59, 59),
    },
  ];